### ISSUE TITLE
Can you update it to be compatible with Repentance+?

### ISSUE THREAD

**Issue by sawalk** [ddeeddii/eztools#7]
Item renaming codes don't work in Repentance+, I don't know if the same is true for other features, but they're probably not compatible.

Can you update it to be compatible with Repentance+?

**Comment by ddeeddii** [comment]
Hi, thanks for the issue.
Currently the Repentance+ modding api is still a bit unstable and REPENTOGON is not yet supported, so the REPENTOGON template working is out of the question.
That being said I'll look into temporarily patching the Vanilla template while the modding api gets fixed.

**Comment by ddeeddii** [comment]
I've looked into the issue, turns out the function that EzItems relies on in the Vanilla template to display the changed item name (`ShowItemText`) is completely broken in Repentance+ and there is nothing on my end that can be done to fix it.
I apologize for the inconvenience but all that can be done at this point is to wait for an official patch which should fix it.

**Comment by ddeeddii** [comment]
FYI, the function got fixed but it got fixed but the text now stacks in a column, as opposed to stacking on top of other text which makes the Vanilla template still broken, just not game-breaking. Again nothing that can be done about it.
[Link to Repentance API issue tracker](https://github.com/epfly6/RepentanceAPIIssueTracker/issues/581)

**Comment by sawalk** [comment]
Is it possible to do fake text methods like the [Stage API?](https://steamcommunity.com/workshop/filedetails/?id=1348031964)

**Comment by ddeeddii** [comment]
Yes, I've been made aware. This fix has made the Vanilla template operational in Repentance+ again. I'll remove the temporary notification as EzItems should now fully work in Repentance+.
